"""Add ClassPost table

Revision ID: 0d69d49b3163
Revises: 
Create Date: 2025-07-26 02:44:51.528696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d69d49b3163'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('class_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('class_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('video_file', sa.VARCHAR(length=100), nullable=True),
    sa.Column('video_link', sa.VARCHAR(length=200), nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('date', sa.VARCHAR(length=20), nullable=True),
    sa.Column('time', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id')
    )
    # ### end Alembic commands ###
